<a href="https://colab.research.google.com/github/SansBasnet/Python-automation/blob/master/Numpy_overview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

my_list = [1,2,3]
type(np.array(my_list))

numpy.ndarray

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [17]:
np.arange(0,11,2) # 2 or the number at the end indicated the step size, here is even numbers

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros

<function numpy.zeros>

In [9]:
np.zeros(5) #returns one diemsional array

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,5)) #creates a matrix of n dimensional array 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(1)

array([1.])

In [15]:
np.ones((1,3))

array([[1., 1., 1.]])

In [16]:
np.linspace (0,11,10) #linearly spaced

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [19]:
np.linspace(0,11,30)

array([ 0.        ,  0.37931034,  0.75862069,  1.13793103,  1.51724138,
        1.89655172,  2.27586207,  2.65517241,  3.03448276,  3.4137931 ,
        3.79310345,  4.17241379,  4.55172414,  4.93103448,  5.31034483,
        5.68965517,  6.06896552,  6.44827586,  6.82758621,  7.20689655,
        7.5862069 ,  7.96551724,  8.34482759,  8.72413793,  9.10344828,
        9.48275862,  9.86206897, 10.24137931, 10.62068966, 11.        ])

In [20]:
np.random.randint(0,10) #random number between 0 and 9 

5

In [22]:
np.random.randint(0,100,(3,3)) # 3*3 is the dimension 

array([[18, 38, 53],
       [58, 58, 34],
       [22, 40, 59]])

In [23]:
np.random.normal

<function RandomState.normal>

In [26]:
np.random.seed(101) #gives the same random numbers. These two codes have to be on the same cell for getting same randint. 

np.random.randint(0,100,10) #10 at the end gives 10 random number, between 0 and 99. 

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [27]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [28]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [29]:
arr.max() #gives the max value in the array

95

In [30]:
arr.min() #min value in the array 

9

In [32]:
arr.mean() #grabes the average

60.8

In [33]:
arr.argmax() #index location of the max value which is 95 in the first index position on the array. 

0

In [34]:
arr.argmin()

7

## Reshape method of an array 

In [35]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [37]:
arr.reshape(2,5) #2 rows by 5 columns reshape command reshapes the array

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [39]:
mat = np.arange(0,100).reshape(10,10)

In [40]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
# If I wanna grab a single element from say the first row, second column,

mat[0,1] #inside matrix mat row 0, column 1

1

In [43]:
mat[4,3]

43

In [45]:
#slicing to grab chunks

mat[:,0] #: for collecting an entire first column and 0 for not collecting any other 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [48]:
mat[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [51]:
#Boolean operation on the matrix

mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [53]:
#Only select true Boolean values then

my_filter = mat >50

In [54]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [55]:
mat[mat>50] #This method is known as Boolean masking or masking in general. 

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])